# Generated by Django 3.0.7 on 2022-10-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='connection_id',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
