# Generated by Django 3.0.7 on 2022-11-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='user',
            new_name='supplier',
        ),
        migrations.AddField(
            model_name='responses',
            name='presentation_exchange_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
