# Generated by Django 3.0.7 on 2022-10-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrant_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='igrantuser',
            name='org',
            field=models.CharField(choices=[('NIL', 'Nil'), ('RAKSA_OY', 'Raksa Oy, Finland'), ('BYGG_AB', 'Bygg Ab, Sweden'), ('BOLAGSVERKET_AB', 'Bolagsverket Ab, Sweden')], default='NIL', max_length=250),
        ),
        migrations.AddField(
            model_name='igrantuser',
            name='org_verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified')], default='UNVERIFIED', max_length=250),
        ),
    ]
