# Generated by Django 3.0.7 on 2022-11-07 10:43

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('igrant_user', '0002_auto_20221031_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='igrantuser',
            name='connection_id',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='igrantuser',
            name='connection_state',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='igrantuser',
            name='fullname',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='igrantuser',
            name='presentation_exchange_id',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='igrantuser',
            name='presentation_record',
            field=django_jsonfield_backport.models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='igrantuser',
            name='presentation_state',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='igrantuser',
            name='user_type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('ISSUER', 'Issuer'), ('BUYER', 'Buyer'), ('SELLER', 'Seller')], default='COMPANY', max_length=8),
        ),
    ]
