# Generated by Django 3.0.7 on 2022-11-08 15:46

from django.db import migrations, models
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('igrant_user', '0003_auto_20221107_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrantuser',
            name='connection_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='igrantuser',
            name='connection_state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='igrantuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='igrantuser',
            name='presentation_exchange_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='igrantuser',
            name='presentation_record',
            field=django_jsonfield_backport.models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='igrantuser',
            name='presentation_state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
