# Generated by Django 3.0.7 on 2022-11-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrant_user', '0004_auto_20221108_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='igrantuser',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='igrantuser',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
