# Generated by Django 3.0.7 on 2022-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrant_user', '0005_auto_20221110_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrantuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
