# Generated by Django 3.0.7 on 2022-11-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igrant_user', '0006_auto_20221117_1654'),
        ('igrant_user', '0006_auto_20221117_1645'),
    ]

    operations = [
    ]
