# Generated by Django 3.0.7 on 2022-11-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igrant_user', '0007_merge_20221117_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igrantuser',
            name='org',
            field=models.CharField(choices=[('NIL', 'Nil'), ('RAKSA_OY', 'Raksa Oy, Finland'), ('BYGG_AB', 'Bygg AB, Sweden'), ('BOLAGSVERKET_AB', 'Bolagsverket AB, Sweden')], default='NIL', max_length=250),
        ),
    ]
