# Generated by Django 3.0.7 on 2022-11-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_tender_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='data_agreement_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='issuer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='submission_status',
            field=models.BooleanField(default=True),
        ),
    ]
