# Generated by Django 3.0.7 on 2022-11-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20221110_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='submission_status',
        ),
    ]
