# Generated by Django 3.0.7 on 2024-05-01 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenID4VCCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_token', models.CharField(blank=True, max_length=256, null=True)),
                ('credential', django_jsonfield_backport.models.JSONField(blank=True, default={})),
                ('status', models.CharField(default='pending', max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
