# Generated by Django 3.0.7 on 2024-05-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_openid4vccertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='openid4vccertificate',
            name='credentialJwt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
