# Generated by Django 3.0.7 on 2024-05-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_openid4vccertificate_credentialjwt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openid4vccertificate',
            name='acceptance_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
