# Generated by Django 3.0.7 on 2024-05-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_auto_20240502_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openid4vccertificate',
            name='credentialJwt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
